### ISSUE TITLE
Performance of taxon search on OTU matching page

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/phylografter#70] opened 2013-07-08 22:22 UTC
Go to http://reelab.net/phylografter/otu/study/1164 and type some letters into the box at the bottom of the "Taxon" column. It takes a very long time to come back - I thought the application had gone away forever, or crashed, but eventually I did get a result.

**Comment by rhr** [comment] 2013-07-09 03:42
Duplicate of https://github.com/OpenTreeOfLife/phylografter/issues/57

**Closed as completed by rhr** 2013-07-09 03:42 UTC
